---
- name: Install systemd-timesyncd
  apt:
    name: 
      - tzdata
      - systemd-timesyncd
    update_cache: yes
  when: ansible_distribution == 'Debian' and ansible_distribution_version >= '11' or ansible_distribution == 'Ubuntu' and ansible_distribution_version >= '20'

- name: Set timezone
  timezone:
    name: "{{ timesync_timezone }}"
  notify: systemd-timesyncd configuration changed

- name: check timesyncd.conf
  stat:
    path: /etc/systemd/timesyncd.conf
  register: register_name
  
- name: Configure systemd-timesyncd
  template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    mode: 0644
    owner: root
    group: root
  notify: systemd-timesyncd configuration changed
  when: register_name.stat.exists

- name: Start and enable systemd-timesyncd
  service:
    name: systemd-timesyncd.service
    enabled: yes
    state: started
  when: ansible_facts.services is defined and ansible_facts.services['systemd-timesyncd.service']['source'] == 'systemd'
