---
- name: Restart systemd-timesyncd
  service:
    name: systemd-timesyncd.service
    state: restarted
  listen: systemd-timesyncd configuration changed
  when: (ansible_facts.services is defined and ansible_facts.services['systemd-timesyncd.service'] is defined  and ansible_facts.services['systemd-timesyncd.service']['source'] == 'systemd') and ((ansible_distribution == 'Debian' and ansible_distribution_major_version|int >= 11) or (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int >= 20))
