---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian_11
    image: debian:11
  - name: debian_12
    image: debian:12
  - name: ubuntu_22.04
    image: ubuntu:22.04
  - name: ubuntu_24.04
    image: ubuntu:24.04
provisioner:
  name: ansible
verifier:
  name: ansible
